Add router + Landing Page
VikeLabs/scheduler-front-end pull request #29
Opened 2020-02-08 06:53 UTC by jbenning97

* Added Router
* The landing route is called Home
* The calendar route is called Main
* Strictly UI, no functionality has been implemented

2020-02-08 07:19 UTC, kerfootj reviewed
The page looks great!

2020-02-08 07:19 UTC, kerfootj commented on src/routes/Home.tsx
> +            <TextFieldPwd id="password" label="Password" type="password" />
Can you add autoComplete="username" to the email TextField and autoComplete="current-password" to the password TextField 

Reference: https://material-ui.com/api/text-field/

2020-02-08 07:19 UTC, kerfootj commented on src/routes/Home.tsx
> +import React from 'react';
Can you rename the routes folder to pages. Trying to some what follow [atomic design](https://bradfrost.com/blog/post/atomic-web-design/). At least as far as organizing components.

2020-02-08 07:19 UTC, kerfootj commented on src/routes/Home.tsx
> +const SigninBtn = styled(Button)({
Can you change the hover color on the button. The text is hard to read when hovering over.

2020-02-08 07:22 UTC, kerfootj commented on src/routes/Home.tsx
> +        <StyledCard>
We'll probably want to extract this to it's own component so we can reuse the same page but swap out Sign In or Sign Up forms

2020-02-10 21:13 UTC, BraidenCutforth requested changes

2020-02-10 21:13 UTC, BraidenCutforth commented on public/index.css
> +}
Nitpick but I think it's standard practice to have a newline at the end of the file.

2020-02-10 21:13 UTC, BraidenCutforth commented on public/index.html
> +    <link rel="stylesheet" href="index.css">
Whatever .tsx file has the component that relies on the css file should import it in that fashion.
I believe the syntax is:
```typescript
import 'path/to/index.css'
```
noting to `../` up the tree from the file as necessary until @kerfootj changes the import style

2020-02-10 21:13 UTC, BraidenCutforth commented on src/App.tsx
> +          <Main />
What is Main vs Home?

2020-02-10 21:13 UTC, BraidenCutforth commented on src/routes/Home.css
> +}
newline

2020-02-10 21:13 UTC, BraidenCutforth commented on src/routes/Home.tsx
> +import './Home.css';
Looks like you already used this import style :+1:

2020-02-10 21:13 UTC, BraidenCutforth commented on src/routes/Home.tsx
> +const ForgotPwdBtn = styled(Button)({
This is a way different css style then Passr uses but it looks WAY more elegant that what we are doing. Let's chat and maybe you can point me in the right direction.

2020-02-10 21:13 UTC, BraidenCutforth commented on src/routes/Home.tsx
> +const Home: React.FC = () => {
Beautiful use of composition 🔥

2020-02-10 21:13 UTC, BraidenCutforth commented on src/routes/Main.tsx
> +const Main: React.FC = () => {
I see what Main is now. I am wondering if there is a better name, but I also can't think of one..

2020-02-10 23:13 UTC, kerfootj commented on src/routes/Main.tsx
> +const Main: React.FC = () => {
I think it will change. I'm just not sure what to right now

2020-02-11 02:27 UTC, jbenning97 commented on src/App.tsx
> +          <Main />
As of now, Main is the page with the calendar, and Home is the landing/sign-in page. Open to renaming them.

2020-02-11 02:58 UTC, kerfootj approved these changes
Looks good

2020-02-11 02:59 UTC, merged