added sem tabs
VikeLabs/scheduler-front-end pull request #37
Opened 2020-02-17 06:17 UTC by jbenning97

* Added a theme object
* Added a navbar (mostly empty, we can add as we go)
* Added semester tabs (called SemTabs)

2020-02-18 02:57 UTC, kerfootj requested changes

2020-02-18 02:57 UTC, kerfootj commented on src/molecules/NavBar/NavBar.tsx
> +        <h2>VikeLabs / </h2>
Can we change these to both be the same size? I think it looks best when they're both h3's but I'll get someone else to take a look at it as well. 

Can we reduce the margin a little bit? I think the navbar is just a bit too tall. 

Also can you link to https://vikelabs.ca/

2020-02-18 02:57 UTC, kerfootj commented on src/molecules/SemTabs/SemTabs.tsx
> +import Theme from '../../atoms/Theme/Theme';
absolute import

2020-02-18 02:57 UTC, kerfootj commented on src/molecules/SemTabs/SemTabs.tsx
> +import React from 'react';
I would appreciate if you renamed this to SemesterTabs but you don't have to. Personally I find longer names easier read but that might just be me.

2020-02-20 01:40 UTC, kerfootj approved these changes

2020-02-20 01:42 UTC, kerfootj requested changes
You have a merge conflict now

2020-02-20 01:53 UTC, jbenning97 commented
@kerfootj Should be g2g now.

2020-02-20 02:05 UTC, kerfootj approved these changes

2020-02-20 02:06 UTC, merged